steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'client/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'client/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['build']
  dir: 'client/'